"""Reference conformance vector identifiers."""

from __future__ import annotations

CONFORMANCE_VECTOR_IDS = [
    "cvEmptyEnv",
    "cvSafeInv",
    "cvBadSequence",
    "cvPrevHashMismatch",
    "cvPermittedActionHashMismatch",
    "cvUnknownActionKind",
    "cvNetworkDenied",
    "cvCredentialHalted",
    "cvPublicOutputDenied",
    "cvCheckerUpdateHalted",
    "cvKernelUpdateHalted",
    "cvUndeclaredToolDenied",
    "cvPackageInstallerDenied",
    "cvReadOutsideEnvelope",
    "cvWriteOutsideEnvelope",
    "cvOpenDecisionPreventsSecond",
    "cvDispatchWithoutIssue",
    "cvConsumeWithoutDispatch",
    "cvDuplicateLedgerSequence",
    "cvHashMismatch",
    "cvCrashAfterDispatchRecovery",
    "cvNoRootContractNoPositiveClaim",
    "cvScratchOnlyNoHostInstallClaim",
    "cvUnknownInterfaceBlocksCompleteClaim",
    "cvIncompleteInventoryKnownInterfaceMax",
    "cvIrreversibleInfoReleaseNotRollbackCertified",
    "cvHumanFeedbackResidueRemainsResidualRisk",
    "cvRetainedAuthorityBlocksAutonomy",
    "cvMissingSeedConsumptionBlocksAutonomy",
    "cvProvisionalClaimGateNonAuthorizing",
    "cvPartialClaimGateNonAuthorizing",
    "cvCertificateMissingCardEvidence",
    "cvCertificateTransitionMismatch",
    "cvModifiedClaimCardHashBlocksAutonomy",
]
